### PR TITLE
Check for the existence of the MPLE

### PR DESCRIPTION
**Pull request by schmid86**
Added a check to test whether the MPLE actually exists. This test is only being executed if estimate="MPLE".
The test uses the rcdd-package. The method was proposed by (Konis 2007). 
Added an explanation of this method in ergm.mple

### CODE REVIEW

**Comment by krivit** [comment]
Thanks! This is a lot easier to review! A few items:
1. How much more difficult and/or inefficient would it be to use the `lpSolveAPI` to do this? It's not a big deal, but I just wanted to make sure the additional dependency was actually necessary.
2. Why is the code checking `if(control$init.method == "MPLE"){`? I would think that if we were in `ergm.mple()`, we'd be wanting the MPLE for *something*.
3. I think that it might be worth putting this into a small helper function. It looks to me like it only needs the `pl` list, and `ergm.mple()` is too long as it is.

**Comment by schmid86** [comment]
Regarding your comments:
1. It should be possible to use `lpSolveAPI` instead of `rcdd`. I will change the code accordingly.
2. I guess it is not necessary to check for `control$initmethod == "MPLE"`. My thinking behind this was that it is especially of interest to check whether the MPLE exists, if the user is only interested in the MPLE, i.e., `estimate="MPLE"`. However, it can also be checked anytime the MPLE is being used for something.
3. Sure, no problem. I will put it into its own helper function.

**Comment by schmid86** [comment]
Replacing `rcdd` with `lpSolveAPI` turned out to be a non-trivial problem. Checking for the existence of the MPLE requires the calculation of the _direction of recession_ (see Geyer (2009): Likelihood inference in exponential families and directions of recession. Electrical Journal of Statistics). The direction of recession is implemented in 'rcdd', but not in 'lpSolveAPI'.

**Comment by krivit** [comment]
Thanks for looking into all this! I'll make a few tweaks to the code and merge, but one thing that we will need to think about is how this applies to *curved* ERGMs, because the version in `dev` supports MPLE for curved models.

**Comment by krivit** [comment]
I've put the tester function into a the same file as `ergm.pl`, deleted the duplicated documentation, and set the `@noRd` flag to avoid generating a help file for an internal function. I then squashed the commits into one.

**Pull request merged**
