### PR TITLE
Improving is.inCH()

### PR DESCRIPTION
**Pull request by schmid86**
The update in is.inCH deals with issue statnet/ergm-private#230 (lpSolve's lp() via is.inCH() hangs for some high-dimensional input) in the ergm-private repository. The problem that has been explained in this issue can be resolved by using the lpSolveAPI package, instead of the lpSolve package.
An interesting side node: The minimal code to reproduce works if the 704th row of the M-matrix is being deleted, i.e., M<- M[-704,]

I benchmarked the old and the new version of is.inCH using the is.inCH.RData from issue statnet/ergm-private#230 and deleting the 704th row. Here are the results:

microbenchmark(is.inCH(p,M))
Unit: milliseconds
expr min lq mean median uq max neval
is.inCH(p, M) 467.2435 486.0108 536.5473 506.7203 558.3606 861.4797 100

microbenchmark(is.inCH.old(p,M))
Unit: milliseconds
expr min lq mean median uq max neval
is.inCH.old(p, M) 889.4864 921.572 1015.41 969.2405 1052.157 1409.839 100

### CODE REVIEW

**Comment by krivit** [comment]
@schmid86 , thanks for putting this together! As far as I can tell, the changes to implement the MPLE covariance are still there, so it's not just a `is.inCH()` patch. Is that what you intended?

**Comment by schmid86** [comment]
@krivit I thought that is what you proposed in the MPLE covariance PR, but I probably misunderstood you then. Do you prefer it if I create a new PR without the MPLE covariance changes and only the `is.inCH()`-changes?

**Comment by krivit** [comment]
@schmid86 , yes, what I was hoping for was a PR that makes only the `is.inCH()` changes. We could merge it quickly, since it's compact and doesn't involve any UI or documentation changes, and focus on finalising the MPLE work.

**Comment by krivit** [comment]
@schmid86 , I can probably excise the non-`is.inCH()` stuff myself, but it looks like your working branch is `master`, and I don't want to clobber what other changes you've made.

**Pull request closed without merging**
