### PR TITLE
Predict ergm

### PR DESCRIPTION
**Pull request by mbojan**
This addresses #6 

@krivit please corroborate at this stage, things that I will still do before merging this PR

- [x] implement `output="matrix"`
- [x] implement conditional and unconditional predicted probabilities
- [x] implement `type` as in `predict.glm()` (not sure if that's useful in practice though...)
- [ ] add doc and examples how `constraints=` can be used to cherry-pick the dyads

### CODE REVIEW

**Comment by mbojan** [comment]
Not sure why @#%^$ CI fails as I did not touch any other files, but I'm on it...

**Comment by mbojan** [comment]
It seems I unnecessarily have `devtools::document()`-ed some other files.

**Comment by krivit** [comment]
Thanks for putting this together, and my apologies for not getting to this sooner. I'm finally done with teaching, so I will have time to look at it in the next few days.

**Comment by mbojan** [comment]
Sure @krivit , np. I had some alternative idea, for `predict.ergm()` but I'll put it together first.

**Comment by krivit** [comment]
> Sure @krivit , np. I had some alternative idea, for `predict.ergm()` but I'll put it together first.

Just to make sure I understand, are you thinking of redoing this PR in a different way? Or do you want me to start reviewing it as it is?

**Comment by mbojan** [comment]
Go ahead @krivit . I was thinking about modification to also have `newdata` argument, so:  `predict.ergm(model, newdata)` but it would be a small change should we decide it makes sense anyway.

**Comment by krivit** [comment]
What would `newdata` be? Another network?

**Comment by mbojan** [comment]
Yep. Some network other than the model was fit to.

pt., 3 sty 2020, 23:08 użytkownik Pavel N. Krivitsky <
notifications@github.com> napisał:

**Comment by mbojan** [comment]
The default would be `newdata=NULL` i.e. use network from `model` object.

sob., 4 sty 2020, 00:15 użytkownik Michał Bojanowski <michal2992@gmail.com>
napisał:

**Comment by mbojan** [comment]
Thanks! So I guess #6 can be closed?

**Pull request merged**
