### PR TITLE
Fix row/colnames of matrix output of predict.formula()

### LINKED ISSUE #226: predict method output working as intended? conditional=TRUE vs. conditional=FALSE
Possibly this is fine, but noticed the differences in format between the two outputs below so checking whether it's as intended.

```r
data(g4)
set.seed(123)
SimpleERGM <- ergm(g4 ~ edges)
## Starting maximum pseudolikelihood estimation (MPLE):
## Evaluating the predictor and response matrix.
## Maximizing the pseudolikelihood.
## Finished MPLE.
## Stopping at the initial estimate.
## Evaluating log-likelihood at the estimate. 
predict(SimpleERGM, conditional = TRUE, output = "matrix")
##           [,1]      [,2]      [,3]      [,4]
## [1,] 0.0000000 0.4166667 0.4166667 0.4166667
## [2,] 0.4166667 0.0000000 0.4166667 0.4166667
## [3,] 0.4166667 0.4166667 0.0000000 0.4166667
## [4,] 0.4166667 0.4166667 0.4166667 0.0000000
predict(SimpleERGM, conditional = FALSE, output = "matrix", nsim = 1000)
##      V1   V2   V3   V4
## V1 0.00 0.40 0.42 0.41
## V2 0.47 0.00 0.39 0.45
## V3 0.38 0.42 0.00 0.40
## V4 0.42 0.40 0.55 0.00
```

### PR DESCRIPTION
**Pull request by mbojan**
Matrix output is now always named with vertex names of the network object, This closes #226 .

### CODE REVIEW

**Comment by mbojan** [comment]
CI failures seem to be related to #233 only.

**Comment by krivit** [comment]
Thanks! @mbojan , do you mind if I tweak the last commit to change the test description and formatting?

**Comment by mbojan** [comment]
Sure.

wt., 2 mar 2021, 07:01 użytkownik Pavel N. Krivitsky <
notifications@github.com> napisał:

**Comment by mbojan** [comment]
@krivit , I sent you an invite so you can push to the branch before merging.

**Comment by krivit** [comment]
> @krivit , I sent you an invite so you can push to the branch before merging.

No need. GH lets the maintainer push to the PR branch.

**Comment by mbojan** [comment]
> No need. GH lets the maintainer push to the PR branch.

OK. Did you ended-up editing anything? Can't really tell from the log.

**Pull request merged**
