### PR TITLE
Convert ERGM term and term-alike documentation to Roxygen and implement dynamic indexing

### PR DESCRIPTION
**Pull request by krivit**
This patch, implemented by @joycecheng and @krivit, implements the new documentation framework discussed in statnet/ergm#274. All terms and term-alikes (constraints, hints, and references) documented in the package have been converted. Proposals have not, as the documentation format for them has not yet been determined.

### CODE REVIEW

**Comment by mbojan** [comment]
I've looked through terms, constraints and references. My observations/questions (in no particular order):

1. Everything seems to work and looks really nice. I think it is much more convenient than the older format as you can reach the man page of a certain term from multiple places: the "big table", lists grouped by concepts etc. This is awesome work!
2. Opening the help pages is slow, at least on my (not so beefy) machine. This is most likely partly because of scanning the loaded packages, partly just because of the size of the page (e.g. for terms). I have not properly tested/measured that though.
3. I was not able (I think) to actually see the outcome of that dynamic scan. I loaded `ergm.count` but could not see the generated links to pages in other packages. Should it work with CRAN version of `ergm.count`? Will it work already with any other Statnet package (CRAN) to see if it works?
4. I guess already on some TODO list: adding examples to term/reference/constraint man pages would be very helpful. At this moment the term docs are quite terse. Having actual model-fitting in the example code will surely blow-up the timings of testing and RCMDchecking. But e.g. for terms I'm thinking of examples consisting of one or more of 
    - create a small graph
    - calculate the suffstat(s)
    - modify the graph by toggling selected dyads
    - calculate the suffstat(s) again illustrating how and why they changed due to the toggles

Great works @joycecheng @krivit (applause) 🚀 🥳 !

**Review by mbojan — APPROVED** [review]
I've looked through terms, constraints and references. My observations/questions (in no particular order):

1. Everything seems to work and looks really nice. I think it is much more convenient than the older format as you can reach the man page of a certain term from multiple places: the "big table", lists grouped by concepts etc. This is awesome work!
2. Opening the help pages is slow, at least on my (not so beefy) machine. This is most likely partly because of scanning the loaded packages, partly just because of the size of the page (e.g. for terms). I have not properly tested/measured that though.
3. I was not able (I think) to actually see the outcome of that dynamic scan. I loaded `ergm.count` but could not see the generated links to pages in other packages. Should it work with CRAN version of `ergm.count`? Will it work already with any other Statnet package (CRAN) to see if it works?
4. I guess already on some TODO list: adding examples to term/reference/constraint man pages would be very helpful. At this moment the term docs are quite terse. Having actual model-fitting in the example code will surely blow-up the timings of testing and RCMDchecking. But e.g. for terms I'm thinking of examples consisting of one or more of 
    - create a small graph
    - calculate the suffstat(s)
    - modify the graph by toggling selected dyads
    - calculate the suffstat(s) again illustrating how and why they changed due to the toggles

Great works @joycecheng @krivit (applause) 🚀 🥳 !

**Comment by krivit** [comment]
> 3\. I was not able (I think) to actually see the outcome of that dynamic scan. I loaded `ergm.count` but could not see the generated links to pages in other packages. Should it work with CRAN version of `ergm.count`? Will it work already with any other Statnet package (CRAN) to see if it works?

It requires extension packages to be converted as well to be indexed. You need to install from `joycecheng/ergm.count@ergm-term-index` for that package.

**Comment by martinamorris** [comment]
I'm afraid I'm going to need a bit of hand-holding to review this.

1. please confirm the commit I should be building from -- I'm assuming I can install using `remotes::install.github("joycecheng/ergm@ergm-term-index")`  but lmk if I should be using something else.  

2. please give examples of the syntax to generate the things i should be checking/reviewing.  thx!

**Comment by krivit** [comment]
@martinamorris , the installation is as you say. There is no special syntax, just `?ergmTerm`, `?ergmConstraint`, etc..

**Pull request merged**
