### PR TITLE
add term isolatededges (undirected only)

### PR DESCRIPTION
**Pull request by chad-klumb**
following discussion on statnet/ergm#95; works on undirected graphs only (including bipartite)

closes statnet/ergm#95

### CODE REVIEW

**Comment by chad-klumb** [comment]
Any objections to me merging this?

**Comment by sgoodreau** [comment]
I'd like to review it, I'm just really swamped right now. Soon, soon.

**Comment by chad-klumb** [comment]
Okay no problem :)

**Comment by krivit** [comment]
Do we still want the "components" term that throws an error on a size >2?

**Comment by sgoodreau** [comment]
Nope, not for now.

**Pull request merged**
