### PR TITLE
Standardised keywords/concepts/categories to keywords in user facing …

### PR DESCRIPTION
**Pull request by joycecheng**
…documentation and functions statnet/ergm#376

### CODE REVIEW

**Comment by joycecheng** [comment]
Checked the otherh repos and there does not seem to be changes required in the other repos.

Only changed the user facing documentation and functions to keep the change set small. Will be a simple search and replace for the other occurances.

**Comment by krivit** [comment]
Is the vignette affected?

**Comment by krivit** [comment]
Also, can you please fix the check errors?

**Comment by krivit** [comment]
Looks like vignettes are affected. @joycecheng , can you please fix?

**Pull request merged**
