### PR TITLE
add ndyads as top-level argument to predict

### PR DESCRIPTION
**Pull request by chad-klumb**
references statnet/ergm#179

### CODE REVIEW

**Comment by krivit** [comment]
I am not sure this one is a good idea, and I don't see a use case for it. As far as I can tell, the user has no control over *which* dyads get predicted, so it's not clear how they are going to use the results. I would rather have the code err out and have the user deal with the problem by, say, specifying the model in two parts. Am I missing something?

**Comment by chad-klumb** [comment]
I don't think there's a way to control which dyads you get, it would be the "random sample" generated by the `MPLE` code.  Conceivably someone could do a reasonable analysis with a sample of dyads instead of a census of dyads, but if that seems unlikely then I guess splitting the model up is the (quite annoying) way to go.

**Comment by krivit** [comment]
It's a bit more complicated than that: you aren't getting a systematic sample of dyads but rather a systematic sample of non-edges, combined with a census of edges. Anyway, maybe this can wait until `dev`. Right now, `dev` *is* vulnerable to the dyads*stats problem, but it can be rewritten not to be, provided that the system can process `.Machine$integer.max*8` = 16GB vectors in a reasonable time frame.

**Comment by chad-klumb** [comment]
I'm fine with waiting until `dev`, ideally making this work even if the number of dyad types alone exceeds `2**31`.

**Pull request closed without merging**
