### PR TITLE
Add modified kvec for TERGM

### PR DESCRIPTION
**Pull request by AdrienLeGuillou**
- changes <stdlib.h> with <R.h>
- replace calls to realloc and free to R_Realloc and R_Free

Contrary to KHash, no allocator macros are defined by default

related to https://github.com/statnet/tergm/pull/125

### CODE REVIEW

**Comment by krivit** [comment]
Hey, sorry take so long on this. Can I trouble you to use a development branch rather than master and make a PR from that? It makes it easier to test on my system.

**Comment by AdrienLeGuillou** [comment]
Hi, no worries.
Do you mean making a dev branch on `ergm` and opening a PR from it to `master`? 
I am not allowed to create branches on this repo though.

**Comment by krivit** [comment]
The idea is to keep `AdrienLeguillou/ergm@master` identical to `statnet/ergm@master` at all times, and make a PR from `AdrienLeguillou/ergm@kvec` to `statnet/ergm@master` .

**Comment by krivit** [comment]
That way, I can check out your dev branch and make edits and comparisons as needed.

**Comment by AdrienLeGuillou** [comment]
got it

**Pull request closed without merging**
